# Generated by Django 5.0.4 on 2024-05-14 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='quadra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arena.quadra'),
        ),
    ]
