# Generated by Django 5.0.4 on 2024-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_remove_quadra_reserva_reserva_quadra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='senha',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(default='', max_length=50),
        ),
    ]
