# Generated by Django 5.0.4 on 2024-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_remove_pessoa_senha_funcionario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
