# Generated by Django 5.0.4 on 2024-05-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_alter_funcionario_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arena.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='arena.endereco'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
