# Generated by Django 5.0.4 on 2024-05-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_remove_cliente_pessoa_remove_funcionario_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.IntegerField(default=-1),
        ),
    ]
