# Generated by Django 5.0.4 on 2024-05-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_alter_cliente_endereco_alter_funcionario_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='arena',
        ),
    ]
